pc:
    wireguard-key: ENC[AES256_GCM,data:aeXKUmfFDi6Z0VyRkFvGr/xbeDfXf7YdbFbJeqXGmcw9G6O85J80gaNwmgw=,iv:Fo1IXeZxKYIB7EO3rh8NkWpRloBsQk9lIkB1mPtLTWM=,tag:Nd0eOaAQj205pZftuj26Zw==,type:str]
sops:
    age:
        - recipient: age1ysccuapykwfkt9sjkd0sd5qltm4dq2sacfxlxkj6sx7wtfr3z3lql8t300
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLalVkWUtpSHlscUpQZTBn
            SFNSTE9zdG9sNTVUanRmSkkxbXlFTmZMcjM0ClhnTnZjRDZIVGliaG1oOHloRHR2
            RGxGQUh5azdPSzduZ2dha0R3UW1raEEKLS0tIG8zdkhVbXZxZE0vWWhUcTVSOHU4
            TTVXcWZYSTZpSEpibjRRQkFVZWNnakEKwiocGAqjF81V7H0VK2U4TFRg2Wg/+xVt
            jJlyXkGhPbk0oUAxItwyyJeYP4cwfvouFoWXQ+NZFdecU8AsP45gjQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1szs3cjcnl2g7mwvhcd4hvtj9mf6fz9nacqqp9m8z25jwr2yrh9lqjwxfam
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRTFkWUhWdTZCU3Y4WU51
            WFFNZE1wLzhsSmlvVHB1MWJWMiswMSsySkVzCjU1U0Jsb3MxQ1FpQnhVOW4wSzFn
            d0ZqQ1VmWGpiRUthYnUxb1pBS01VdGcKLS0tIGhSY0ZuSUhRNjNkb1dMd0VSaVpK
            bWJSaGh0THYyR0V5Vm1XZjQ4c0U4YTQKuB9Fcv5/hJNEtHtRHcebwOAft0l2/qXy
            Ef/jQhxCMZLs4C+P6wCpdjUN7qLPKenaaj48eEvrc+JGTb/5xYWpJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-29T20:20:15Z"
    mac: ENC[AES256_GCM,data:1vjKKJh8aaP+zIoDeIfu5UPRNrZRe1kVaz2A32PaC4CmjPhRzZzh3lEhYZFqJvfYTkfuNQezJmo4TgpHVs91n0YiQFkBQ3jU+TP3GUlSKC3pH3inN3Iy9+PM+XblpOHtZk2RGWQ3/JwzRPm6cHfKLL4MSnB1MB+T7r1OLktT1iI=,iv:gNPYuGU90RNu3zrZqJigfHIHa9fokv3g0KuZzOAzwgs=,tag:1wC/FJdgHXp4rtgjXUl7rA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
