pc:
    wireguard-key: ENC[AES256_GCM,data:aeXKUmfFDi6Z0VyRkFvGr/xbeDfXf7YdbFbJeqXGmcw9G6O85J80gaNwmgw=,iv:Fo1IXeZxKYIB7EO3rh8NkWpRloBsQk9lIkB1mPtLTWM=,tag:Nd0eOaAQj205pZftuj26Zw==,type:str]
sops:
    age:
        - recipient: age1ysccuapykwfkt9sjkd0sd5qltm4dq2sacfxlxkj6sx7wtfr3z3lql8t300
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NlRqQ2ZmRFNBTFZlQURl
            Skh0QzhTTkpkV1dLWTk4WlZYS2thbERLSDNVCndzME45dWlXS05INE5GaFlPb1F2
            WHBOenNVT2dKakgweWdoYTExL1J1T3MKLS0tIEJkY3pwZWRnSWZRbHZKVnkya3hl
            WFk5dFoyRFVIYUVwdldkUG83VXVnOGcKAoVdCaXGykwHsYf0nDgJby+Ff9W+Qmg9
            SNbr0LuZRTI1rX+r2WhongbVRTRignxQ6Ut909Ch9H8Yie1GM9CUqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1szs3cjcnl2g7mwvhcd4hvtj9mf6fz9nacqqp9m8z25jwr2yrh9lqjwxfam
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdmFuZlFneEE1Y21uVEZo
            K0VQcHd3QW5lNmZ6K3dpOXZOT1M5RC80NDBFCk9ZRjZ4MFZLOEZXMzdZUWg2eVhz
            OU5NRWpVSG0wREtoTXNyWXBhS25XT0UKLS0tIElwaEk2VHE2L3QrdkZPQVE5TDY0
            N3RWcjBSMHEzM0JzK0twQlQvVTNralkKRJuVmYoqWJ/QHbSuc1J1UR/fHz8kJr6f
            vDkCAVjlD/+lDlc2S2xpPD9SpDT+xb3FQjt5Y5IVHshoc/TaSMeP9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zf7e9t3d38v04t3msxw3f5hnyxuyngnw0wu07qfl0cmxkwfxwcds73xqj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QWk1eklaNmFHTTRrcUVJ
            SkRtSUxXZmpCVFRTY2UrT21yOThTSTM5cVZNCnJQeGppVGdmbTNlMjJVT2NJYXZk
            a3NuRkFHR0hiQkhhWnNYREQ2WC9PRGsKLS0tIFNaWndLZjliRXRkTHgxbzdwZit6
            OFp6ZkhSMmVZZ2lPeFpQOFdJWFJ1Zm8KHwuzW8vGbqMPckivwtC/I0yQqPaQFREI
            RktMnAeIg6bgWzd6tCTGWCpXMtN938vKsQU1MToCSpMNdiZs1Kt0zQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-29T20:20:15Z"
    mac: ENC[AES256_GCM,data:1vjKKJh8aaP+zIoDeIfu5UPRNrZRe1kVaz2A32PaC4CmjPhRzZzh3lEhYZFqJvfYTkfuNQezJmo4TgpHVs91n0YiQFkBQ3jU+TP3GUlSKC3pH3inN3Iy9+PM+XblpOHtZk2RGWQ3/JwzRPm6cHfKLL4MSnB1MB+T7r1OLktT1iI=,iv:gNPYuGU90RNu3zrZqJigfHIHa9fokv3g0KuZzOAzwgs=,tag:1wC/FJdgHXp4rtgjXUl7rA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
